# Generated by Django 4.1 on 2023-01-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags_app', '0002_student_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=6),
        ),
    ]
