# Generated by Django 4.1 on 2023-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags_app', '0003_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.FloatField(max_length=20),
        ),
    ]
